apiVersion: 1.0.0
kind: Plugin
metadata:
  name: Sumologic Logger
  description: Sumologic Logger plugin
  icon: asset/icon/reekoh200x200.png
  signupLink: https://myservice.com/signup # ??
  type: Logger
  price: 0
  tags:
    - logger
    - sumologic

  release:
    version: 1.0.0
    notes: path/to/RELEASENOTESv1.0.0.md # ??
    documentation: README.md
    config:
      httpSource:
        label: Http Source
        type: String
        maxLength: 1000
        required: true
        help: Specify your Sumologic Http Source.